### ISSUE TITLE
Chezmoi Developers Collaborate!

### ISSUE THREAD

**Issue by ProfessorManhattan** [azmodude/dotfiles#2]
Hey, I'm trying to start a channel for Chezmoi developers with lots of commits... check out this Gitter https://gitter.im/megabyte-labs/community# and we can chat. I've been working on a cross-platform installer that shapes the OS into similar platforms in terms of tools. I'm also a UI developer by trade so its looking pretty sweet. I've been cherry picking code from other Chezmoi projects and more... would love to chat

**Comment by azmodude** [comment]
No thanks and definitely no thanks for the spam.
